### ISSUE TITLE
[BUG] Fix the groups page

### ISSUE THREAD

**Issue by albert118** [albert118/Studio-Management-System#101]
The groups page isn't pulling real member data for the rows and also has an extra button for creating a group.

Let's correct the data hook usage in the container and double check the mappings. While we're here we can also remove the extra button on the top left of the page.

![image](https://user-images.githubusercontent.com/26985949/234912026-24aeea42-d0d9-4b16-b785-f09bb4d018c4.png)

**Comment by willyyto** [comment]
This is working fine on mine. It might be because you dont have a group assigned to the studentcontact

**Comment by willyyto** [comment]
![image](https://user-images.githubusercontent.com/7985511/235086578-5703ee79-17ef-481f-a6ae-3add7a585041.png)

**Comment by albert118** [comment]
sike never accepted any invitiations
