### ISSUE TITLE
Develop Docker Deployment

### ISSUE THREAD

**Issue by Ryan-Cleminson** [albert118/Studio-Management-System#15]
Related issues,

* #13 
* #7 
* #11
* #12
* #26
* #93

**Comment by albert118** [comment]
To develop the docker deployment, we should add a prod Dockerfile config. This should disable starting the code in dev mode at least and include an SSL cert for deploying to the web.

This should also double-check the env secrets.

**Comment by albert118** [comment]
Related issues,

#13 
#7 
#11
#12
#26

**Comment by albert118** [comment]
This issue is more of a parent issue that's a catch-all for what the related issues don't cover.

**Comment by albert118** [comment]
security still in progress

**Comment by albert118** [comment]
Assigned @JaydenL33 as @Ryan-Cleminson isn't doing the sec work

**Comment by albert118** [comment]
Closing, as remaining work is captured by in progress sec tickets
