### ISSUE TITLE
Development Of Backend Functionality

### ISSUE THREAD

**Issue by willyyto** [albert118/Studio-Management-System#27]
Add the domain model interaction

- [x] #44
- [ ] #46
- [ ] add some biz' services to handle the simple DTO workflows

**Comment by JaydenL33** [comment]
Do we know if we are using a bespoke C# API or are we using Supabase

**Comment by JaydenL33** [comment]
#54 Related to this, and will answer this question.

**Comment by albert118** [comment]
#54 synopsis, 

We will be using Supabase auth and a .NET backend.

**Comment by albert118** [comment]
> Do we know if we are using a bespoke C# API or are we using Supabase

This issue aims to capture work done in the backend. Not the infrastructure or language choices.

Several previous infrastructure issues (tagged 'infrastructure') covered that work.
