### ISSUE TITLE
Development Of Frontend Functionality

### ISSUE THREAD

**Issue by willyyto** [albert118/Studio-Management-System#28]
We need a couple of frontend views to kick off the MVP

- [x] some dashboard content
- [ ] #47
- [x] #48

**Comment by Ryan-Cleminson** [comment]
@albert118 issue was found on the group page with a description leading to ... instead of a new line.

<img width="1496" alt="Screenshot 2023-05-04 at 3 06 11 pm" src="https://user-images.githubusercontent.com/40050014/236116709-372e8903-a47a-4896-8f9b-a193a3d044e2.png">

**Comment by albert118** [comment]
Open a bug for that @RyanCleminson, 
there's a word break mixing there that shouldn't be

**Comment by Ryan-Cleminson** [comment]
Bug report here (I will address the it): #110
